# TODO remove after pending PR is merged https://github.com/tilt-dev/tilt-extensions/pull/295
def wait_for(url):
    return """while [[ "$(curl -s -o /dev/null -w ''%{{http_code}}'' {})" != "200" ]]; do sleep 5; done""".format(url)

DEFAULT_HASURA_SECRET = 'hasura-dev-secret'

def hasura_console(release_name='',
            path='.', 
            hasura_resource_name='hasura',
            hasura_secret=DEFAULT_HASURA_SECRET,
            hasura_endpoint= 'http://localhost:8080',
            wait_for_services=[]):
    # * Wait for Hasura, then run the console locally
    #  ? fetch admin secret from k8s?
    #  "--admin-secret `kubectl get secret {} -o jsonpath='{{.data.adminSecret}}' | base64 -D`".format(hasura_resource),
    console_options = '--project {} --endpoint {} --admin-secret {}'.format(
        path,
        hasura_endpoint,
        hasura_secret
    )
    config = read_yaml(os.path.join(path, 'config.yaml'), False)
    if not config:
        local('mkdir -p {}'.format(os.path.join(path, '..')))
        local('hasura init {} --version 3 --endpoint {}'.format(path, hasura_endpoint))
        # * Bug in the latest hasura cli version - set metadata version.yaml to 3
        # local('echo "version: 3" > {}'.format(
        #     os.path.join(path, 'metadata/version.yaml')))

    serve_cmds = [
        'hasura migrate apply {} --all-databases'.format(console_options),
        '[ $(wc -c <"{}/metadata/databases/databases.yaml") -ge 4 ] && hasura metadata apply {} || hasura metadata export {}'.format(path, console_options, console_options),
        'hasura console {}'.format(console_options)
    ]
    hasura_resource = '{}-{}'.format(release_name,
                                     hasura_resource_name) if release_name else hasura_resource_name
    console_resource = '{}-hasura-console'.format(
        release_name) if release_name else 'hasura-console'
    local_resource(console_resource,
                    '\n'.join([wait_for(x) for x in wait_for_services + ['{}/healthz'.format(hasura_endpoint)]]),
                   resource_deps=[hasura_resource],
                   serve_cmd=' && '.join(serve_cmds),
                   allow_parallel=True,
                   links=[link('http://localhost:9695/', 'Hasura Console')])